title: How can hard waste material be contagious for your health?
description: >-
  The asbestos problem is one of the problems that human beings ignore because
  of having a lack of knowledge about what type of health problems it can
  cause. 
steps:
  - course: githubtraining/introduction-to-github
    description: The first step in your course
  - link: 'https://lab.github.com'
    title: Check out Learning Lab for more courses!
    description: >-
      There are many more courses available on Learning Lab for you to check
      out.
